apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.3.3
  # (disabled) volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
  - name: pod
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        # Name must be "elasticsearch-data"
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    podTemplate:
      metadata:
        annotations:
          linkerd.io/inject: enabled
        labels:
          app: elasticsearch
      spec:
        automountServiceAccountToken: true
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: elastic
                topologyKey: kubernetes.io/hostname
        containers:
        - name: elasticsearch
          # OK:   mem=768M, cpu=500m, JVM=256M
          # Fails: mem=512M, cpu=750m, JVM=256M
          resources:
            requests:
              memory: "768Mi"
              cpu: "500m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms256m -Xmx256m"


  # secureSettings:
  # - secretName: elastic-certificates

  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        # expose this cluster Service with a LoadBalancer
        type: ClusterIP
    # tls:
    #   selfSignedCertificate:
    #     # add a list of SANs into the self-signed HTTP certificate
    #     subjectAltNames:
    #     - ip: 192.168.1.2
    #     - ip: 192.168.1.3
    #     - dns: elasticsearch-sample.example.com
    #   certificate:
    #     secretName: elastic-certificates
