# Apply manually (kubectl apply...)

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-template-appset-frontend
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: gitops-template-dev
        url: https://kubernetes.default.svc
      - namespace: gitops-template-stage
        url: https://kubernetes.default.svc
      - namespace: gitops-template-prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{namespace}}-frontend'
    spec:
      project: gitops-template-project
      source:
        repoURL: https://github.com/cuttle-ltd/gitops-template.git
        targetRevision: HEAD
        path: frontend
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: false
